server:
  port: 3000
spring:
  config:
    import: "optional:file:backend/.env[.properties]"
  application:
    name: book-community
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  mail:
    host: "${MAILGUN_HOST}"
    port: "${MAILGUN_PORT}"
    username: "${MAILGUN_USERNAME}"
    password: "${MAILGUN_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  security:
    jwt:
      access-token-expiration: 86400000 #24 hours for local, 15 minutes recommanded for production
      refresh-token-expiration: 604800000 # 7 days
    disposable-email: mailinator, 10minutemail, tempmail, throwawaymail, yopmail, fakeinbox, trashmail, sharklasers, dispostable, getnada, maildrop, mintemail, mohmal, temp-mail, tempinbox, mailnesia, guerrillamail









